apiVersion: v1
kind: Namespace
metadata:
  name: adguard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work-pvc
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-conf-pvc
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard
  namespace: adguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard
  template:
    metadata:
      labels:
        app: adguard
    spec:
      containers:
      - name: adguard
        image: adguard/adguardhome:latest
        ports:
        - name: dns-udp
          containerPort: 53
          protocol: UDP
          hostPort: 53
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
          hostPort: 53
        - name: ui
          containerPort: 3000
          protocol: TCP
          hostPort: 30000
        - name: dashboard
          containerPort: 80
          protocol: TCP
          hostPort: 30080
        volumeMounts:
        - name: work
          mountPath: /opt/adguardhome/work
        - name: conf
          mountPath: /opt/adguardhome/conf
      volumes:
      - name: work
        persistentVolumeClaim:
          claimName: adguard-work-pvc
      - name: conf
        persistentVolumeClaim:
          claimName: adguard-conf-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-svc
  namespace: adguard
spec:
  selector:
    app: adguard
  ports:
  - name: dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    targetPort: 53
    protocol: TCP
  - name: ui
    port: 3000
    targetPort: 3000
    protocol: TCP
  - name: dashboard
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP

