expose:
  type: ingress
  tls:
    enabled: false
  ingress:
    hosts:
      core: harbor.anton.local
      notary: notary.anton.local
externalURL: "http://harbor.anton.local"
harborAdminPassword: "Harbor12345!!"

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      size: 50Gi
    chartmuseum:
      size: 1Gi
    jobservice:
      size: 1Gi
    database:
      size: 1Gi
    redis:
      size: 1Gi
