apiVersion: v1
kind: Namespace
metadata:
  name: vpn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-config
  namespace: vpn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  namespace: vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: wireguard
          image: linuxserver/wireguard:latest
          securityContext:
            privileged: true
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Zagreb"
            - name: SERVERURL
              value: "192.168.1.111"
            - name: SERVERPORT
              value: "51820"
            - name: PEERS
              value: "2"   # number of client configs
            - name: PEERDNS
              value: "192.168.1.111"  # << your AdGuard node IP here
            - name: INTERNAL_SUBNET
              value: "192.168.2.0/24"  # << your LAN subnet
          volumeMounts:
            - name: wg-config
              mountPath: /config
            - name: modules
              mountPath: /lib/modules
              readOnly: true
      volumes:
        - name: wg-config
          persistentVolumeClaim:
            claimName: wg-config
        - name: modules
          hostPath:
            path: /lib/modules
